<a href="https://colab.research.google.com/github/itshimashis/important_codes/blob/main/assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Assignment 1 -Soft computing
## Himashis Biswas
#2021csb047

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv("./iris.data")

In [ ]:
data

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [ ]:
data=data.drop(["Iris-setosa"],axis=1)

In [ ]:
data.dtypes

5.1    float64
3.5    float64
1.4    float64
0.2    float64
dtype: object

In [ ]:
for col in data.columns:
    data[col]=data[col]/data[col].abs().max()

In [ ]:
data

          5.1       3.5       1.4   0.2
0    0.620253  0.681818  0.202899  0.08
1    0.594937  0.727273  0.188406  0.08
2    0.582278  0.704545  0.217391  0.08
3    0.632911  0.818182  0.202899  0.08
4    0.683544  0.886364  0.246377  0.16
..        ...       ...       ...   ...
144  0.848101  0.681818  0.753623  0.92
145  0.797468  0.568182  0.724638  0.76
146  0.822785  0.681818  0.753623  0.80
147  0.784810  0.772727  0.782609  0.92
148  0.746835  0.681818  0.739130  0.72

[149 rows x 4 columns]

In [ ]:
row,col=(149,149)
matrix=[[0.0]*col]*row

In [ ]:
#data['5.1'][2]
data['5.1'][2]

0.5822784810126581

In [ ]:
data1=data.copy()

In [ ]:
data1=data1.to_numpy()

In [ ]:
data1

array([[0.62025316, 0.68181818, 0.20289855, 0.08      ],
       [0.59493671, 0.72727273, 0.1884058 , 0.08      ],
       [0.58227848, 0.70454545, 0.2173913 , 0.08      ],
       [0.63291139, 0.81818182, 0.20289855, 0.08      ],
       [0.6835443 , 0.88636364, 0.24637681, 0.16      ],
       [0.58227848, 0.77272727, 0.20289855, 0.12      ],
       [0.63291139, 0.77272727, 0.2173913 , 0.08      ],
       [0.55696203, 0.65909091, 0.20289855, 0.08      ],
       [0.62025316, 0.70454545, 0.2173913 , 0.04      ],
       [0.6835443 , 0.84090909, 0.2173913 , 0.08      ],
       [0.60759494, 0.77272727, 0.23188406, 0.08      ],
       [0.60759494, 0.68181818, 0.20289855, 0.04      ],
       [0.5443038 , 0.68181818, 0.15942029, 0.04      ],
       [0.73417722, 0.90909091, 0.17391304, 0.08      ],
       [0.72151899, 1.        , 0.2173913 , 0.16      ],
       [0.6835443 , 0.88636364, 0.1884058 , 0.16      ],
       [0.64556962, 0.79545455, 0.20289855, 0.12      ],
       [0.72151899, 0.86363636, 0.24637681, 0.12      ],
       [0.64556962, 0.86363636, 0.2173913 , 0.12      ],
       [0.6835443 , 0.77272727, 0.24637681, 0.08      ],
       [0.64556962, 0.84090909, 0.2173913 , 0.16      ],
       [0.58227848, 0.81818182, 0.14492754, 0.08      ],
       [0.64556962, 0.75      , 0.24637681, 0.2       ],
       [0.60759494, 0.77272727, 0.27536232, 0.08      ],
       [0.63291139, 0.68181818, 0.23188406, 0.08      ],
       [0.63291139, 0.77272727, 0.23188406, 0.16      ],
       [0.65822785, 0.79545455, 0.2173913 , 0.08      ],
       [0.65822785, 0.77272727, 0.20289855, 0.08      ],
       [0.59493671, 0.72727273, 0.23188406, 0.08      ],
       [0.60759494, 0.70454545, 0.23188406, 0.08      ],
       [0.6835443 , 0.77272727, 0.2173913 , 0.16      ],
       [0.65822785, 0.93181818, 0.2173913 , 0.04      ],
       [0.69620253, 0.95454545, 0.20289855, 0.08      ],
       [0.62025316, 0.70454545, 0.2173913 , 0.04      ],
       [0.63291139, 0.72727273, 0.17391304, 0.08      ],
       [0.69620253, 0.79545455, 0.1884058 , 0.08      ],
       [0.62025316, 0.70454545, 0.2173913 , 0.04      ],
       [0.55696203, 0.68181818, 0.1884058 , 0.08      ],
       [0.64556962, 0.77272727, 0.2173913 , 0.08      ],
       [0.63291139, 0.79545455, 0.1884058 , 0.12      ],
       [0.56962025, 0.52272727, 0.1884058 , 0.12      ],
       [0.55696203, 0.72727273, 0.1884058 , 0.08      ],
       [0.63291139, 0.79545455, 0.23188406, 0.24      ],
       [0.64556962, 0.86363636, 0.27536232, 0.16      ],
       [0.60759494, 0.68181818, 0.20289855, 0.12      ],
       [0.64556962, 0.86363636, 0.23188406, 0.08      ],
       [0.58227848, 0.72727273, 0.20289855, 0.08      ],
       [0.67088608, 0.84090909, 0.2173913 , 0.08      ],
       [0.63291139, 0.75      , 0.20289855, 0.08      ],
       [0.88607595, 0.72727273, 0.68115942, 0.56      ],
       [0.81012658, 0.72727273, 0.65217391, 0.6       ],
       [0.87341772, 0.70454545, 0.71014493, 0.6       ],
       [0.69620253, 0.52272727, 0.57971014, 0.52      ],
       [0.82278481, 0.63636364, 0.66666667, 0.6       ],
       [0.72151899, 0.63636364, 0.65217391, 0.52      ],
       [0.79746835, 0.75      , 0.68115942, 0.64      ],
       [0.62025316, 0.54545455, 0.47826087, 0.4       ],
       [0.83544304, 0.65909091, 0.66666667, 0.52      ],
       [0.65822785, 0.61363636, 0.56521739, 0.56      ],
       [0.63291139, 0.45454545, 0.50724638, 0.4       ],
       [0.74683544, 0.68181818, 0.60869565, 0.6       ],
       [0.75949367, 0.5       , 0.57971014, 0.4       ],
       [0.7721519 , 0.65909091, 0.68115942, 0.56      ],
       [0.70886076, 0.65909091, 0.52173913, 0.52      ],
       [0.84810127, 0.70454545, 0.63768116, 0.56      ],
       [0.70886076, 0.68181818, 0.65217391, 0.6       ],
       [0.73417722, 0.61363636, 0.5942029 , 0.4       ],
       [0.78481013, 0.5       , 0.65217391, 0.6       ],
       [0.70886076, 0.56818182, 0.56521739, 0.44      ],
       [0.74683544, 0.72727273, 0.69565217, 0.72      ],
       [0.7721519 , 0.63636364, 0.57971014, 0.52      ],
       [0.79746835, 0.56818182, 0.71014493, 0.6       ],
       [0.7721519 , 0.63636364, 0.68115942, 0.48      ],
       [0.81012658, 0.65909091, 0.62318841, 0.52      ],
       [0.83544304, 0.68181818, 0.63768116, 0.56      ],
       [0.86075949, 0.63636364, 0.69565217, 0.56      ],
       [0.84810127, 0.68181818, 0.72463768, 0.68      ],
       [0.75949367, 0.65909091, 0.65217391, 0.6       ],
       [0.72151899, 0.59090909, 0.50724638, 0.4       ],
       [0.69620253, 0.54545455, 0.55072464, 0.44      ],
       [0.69620253, 0.54545455, 0.53623188, 0.4       ],
       [0.73417722, 0.61363636, 0.56521739, 0.48      ],
       [0.75949367, 0.61363636, 0.73913043, 0.64      ],
       [0.6835443 , 0.68181818, 0.65217391, 0.6       ],
       [0.75949367, 0.77272727, 0.65217391, 0.64      ],
       [0.84810127, 0.70454545, 0.68115942, 0.6       ],
       [0.79746835, 0.52272727, 0.63768116, 0.52      ],
       [0.70886076, 0.68181818, 0.5942029 , 0.52      ],
       [0.69620253, 0.56818182, 0.57971014, 0.52      ],
       [0.69620253, 0.59090909, 0.63768116, 0.48      ],
       [0.7721519 , 0.68181818, 0.66666667, 0.56      ],
       [0.73417722, 0.59090909, 0.57971014, 0.48      ],
       [0.63291139, 0.52272727, 0.47826087, 0.4       ],
       [0.70886076, 0.61363636, 0.60869565, 0.52      ],
       [0.72151899, 0.68181818, 0.60869565, 0.48      ],
       [0.72151899, 0.65909091, 0.60869565, 0.52      ],
       [0.78481013, 0.65909091, 0.62318841, 0.52      ],
       [0.64556962, 0.56818182, 0.43478261, 0.44      ],
       [0.72151899, 0.63636364, 0.5942029 , 0.52      ],
       [0.79746835, 0.75      , 0.86956522, 1.        ],
       [0.73417722, 0.61363636, 0.73913043, 0.76      ],
       [0.89873418, 0.68181818, 0.85507246, 0.84      ],
       [0.79746835, 0.65909091, 0.8115942 , 0.72      ],
       [0.82278481, 0.68181818, 0.84057971, 0.88      ],
       [0.96202532, 0.68181818, 0.95652174, 0.84      ],
       [0.62025316, 0.56818182, 0.65217391, 0.68      ],
       [0.92405063, 0.65909091, 0.91304348, 0.72      ],
       [0.84810127, 0.56818182, 0.84057971, 0.72      ],
       [0.91139241, 0.81818182, 0.88405797, 1.        ],
       [0.82278481, 0.72727273, 0.73913043, 0.8       ],
       [0.81012658, 0.61363636, 0.76811594, 0.76      ],
       [0.86075949, 0.68181818, 0.79710145, 0.84      ],
       [0.72151899, 0.56818182, 0.72463768, 0.8       ],
       [0.73417722, 0.63636364, 0.73913043, 0.96      ],
       [0.81012658, 0.72727273, 0.76811594, 0.92      ],
       [0.82278481, 0.68181818, 0.79710145, 0.72      ],
       [0.97468354, 0.86363636, 0.97101449, 0.88      ],
       [0.97468354, 0.59090909, 1.        , 0.92      ],
       [0.75949367, 0.5       , 0.72463768, 0.6       ],
       [0.87341772, 0.72727273, 0.82608696, 0.92      ],
       [0.70886076, 0.63636364, 0.71014493, 0.8       ],
       [0.97468354, 0.63636364, 0.97101449, 0.8       ],
       [0.79746835, 0.61363636, 0.71014493, 0.72      ],
       [0.84810127, 0.75      , 0.82608696, 0.84      ],
       [0.91139241, 0.72727273, 0.86956522, 0.72      ],
       [0.78481013, 0.63636364, 0.69565217, 0.72      ],
       [0.7721519 , 0.68181818, 0.71014493, 0.72      ],
       [0.81012658, 0.63636364, 0.8115942 , 0.84      ],
       [0.91139241, 0.68181818, 0.84057971, 0.64      ],
       [0.93670886, 0.63636364, 0.88405797, 0.76      ],
       [1.        , 0.86363636, 0.92753623, 0.8       ],
       [0.81012658, 0.63636364, 0.8115942 , 0.88      ],
       [0.79746835, 0.63636364, 0.73913043, 0.6       ],
       [0.7721519 , 0.59090909, 0.8115942 , 0.56      ],
       [0.97468354, 0.68181818, 0.88405797, 0.92      ],
       [0.79746835, 0.77272727, 0.8115942 , 0.96      ],
       [0.81012658, 0.70454545, 0.79710145, 0.72      ],
       [0.75949367, 0.68181818, 0.69565217, 0.72      ],
       [0.87341772, 0.70454545, 0.7826087 , 0.84      ],
       [0.84810127, 0.70454545, 0.8115942 , 0.96      ],
       [0.87341772, 0.70454545, 0.73913043, 0.92      ],
       [0.73417722, 0.61363636, 0.73913043, 0.76      ],
       [0.86075949, 0.72727273, 0.85507246, 0.92      ],
       [0.84810127, 0.75      , 0.82608696, 1.        ],
       [0.84810127, 0.68181818, 0.75362319, 0.92      ],
       [0.79746835, 0.56818182, 0.72463768, 0.76      ],
       [0.82278481, 0.68181818, 0.75362319, 0.8       ],
       [0.78481013, 0.77272727, 0.7826087 , 0.92      ],
       [0.74683544, 0.68181818, 0.73913043, 0.72      ]])

In [ ]:
#import math
#for i in range(0,148):
   # for j in range(0,148):
       # val=0
       # for k in range(0,3):
          #  val=val+(data1[i][k]-data1[j][k])*(data1[i][k]-data1[j][k])
       # val=math.sqrt(val)
       # matrix[i][j]=val

In [ ]:
rows=149
cols=149
sim_matrix=[]

In [ ]:
import math

# Assuming 'arr' is a 2D array containing the data and 'matrix' is a 2D array for storing the distances
# Make sure to initialize the 'matrix' array before running this code

for i in range(149):
    temp=[]
    for j in range(149):
        val = 0
        for k in range(4):
            val += (data1[i][k] - data1[j][k]) * (data1[i][k] - data1[j][k])
        val = math.sqrt(val)
        temp.append(val)

    sim_matrix.append(temp)

In [ ]:
df=pd.DataFrame(sim_matrix)
df

,0,1,2,3,4,5,6,7,8,9,...,139,140,141,142,143,144,145,146,147,148
0,0.000000,0.054010,0.046569,0.136950,0.232669,0.106332,0.092923,0.067248,0.048235,0.171831,...,1.094231,1.028471,0.876112,1.091256,1.136366,1.029957,0.882570,0.928825,1.037790,0.844493
1,0.054010,0.000000,0.038948,0.099582,0.207176,0.063533,0.065942,0.079378,0.059980,0.146985,...,1.107868,1.042577,0.893308,1.104856,1.147888,1.044619,0.903479,0.944379,1.047280,0.859091
2,0.046569,0.038948,0.000000,0.125248,0.224839,0.080367,0.084926,0.054010,0.055155,0.169852,...,1.094595,1.030812,0.875185,1.091011,1.135622,1.031660,0.885777,0.929680,1.034765,0.842263
3,0.136950,0.099582,0.125248,0.000000,0.124510,0.078929,0.047709,0.176290,0.121998,0.057361,...,1.097329,1.031456,0.895566,1.091380,1.133896,1.036243,0.907849,0.936133,1.032862,0.853650
4,0.232669,0.207176,0.224839,0.124510,0.000000,0.163274,0.150722,0.275620,0.228700,0.096469,...,1.009756,0.943142,0.824470,1.002410,1.042755,0.950693,0.838422,0.853303,0.942503,0.776048
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,1.029957,1.044619,1.031660,1.036243,0.950693,1.011051,1.023580,1.046029,1.055640,1.022513,...,0.074008,0.036980,0.208417,0.111885,0.127671,0.000000,0.204737,0.122641,0.114501,0.224644
145,0.882570,0.903479,0.885777,0.907849,0.838422,0.877472,0.888041,0.894829,0.908680,0.898364,...,0.262145,0.223994,0.079259,0.268196,0.321735,0.204737,0.000000,0.126469,0.266383,0.131480
146,0.928825,0.944379,0.929680,0.936133,0.853303,0.912034,0.922096,0.944921,0.952198,0.922303,...,0.173546,0.133005,0.119625,0.167929,0.224813,0.122641,0.126469,0.000000,0.157945,0.111258
147,1.037790,1.047280,1.034765,1.032862,0.942503,1.008505,1.023789,1.051899,1.060942,1.019791,...,0.105331,0.119960,0.235295,0.114392,0.113193,0.114501,0.266383,0.157945,0.000000,0.227150
148,0.844493,0.859091,0.842263,0.853650,0.776048,0.826370,0.838484,0.856571,0.866690,0.843284,...,0.271334,0.237781,0.080056,0.261701,0.317592,0.224644,0.131480,0.111258,0.227150,0.000000

In [ ]:
#now calculating the average similarity for every element
#in our case the lesser is better.
average=[]
for i in range(149):
    val=0
    for j in range(149):
        val+=sim_matrix[i][j]

    val=val/149
    average.append(val)

In [ ]:
average

[0.5831568021090938,
 0.5905530255994863,
 0.5822128889965962,
 0.5880693084739707,
 0.5587359320706745,
 0.5725882575242258,
 0.57270207976725,
 0.6035077009725947,
 0.5972425534563668,
 0.5861036079361324,
 0.5720845797354758,
 0.6083347022150905,
 0.647526015130744,
 0.6359634122388287,
 0.6289828839878641,
 0.5833975250527788,
 0.5630080423350137,
 0.567419057891319,
 0.5767362270483116,
 0.561771081921617,
 0.5549698981679967,
 0.6302821504535369,
 0.5167300696175032,
 0.5610381891419663,
 0.5701368177552854,
 0.5356280242722015,
 0.5744130221728271,
 0.5771879725392949,
 0.572321101830258,
 0.5706491735585674,
 0.5391628639613084,
 0.6468053541282996,
 0.6412523812288987,
 0.5972425534563668,
 0.5919125305068351,
 0.5892784962742555,
 0.5972425534563668,
 0.6061152805070157,
 0.5714602472097593,
 0.5716704225413944,
 0.6316992157411038,
 0.6027601915841398,
 0.5228654869432982,
 0.5433262907463083,
 0.5676708718610727,
 0.5900812436735502,
 0.5871134425352854,
 0.5858635852301866,
 0.5770321096132751,
 0.412884172351627,
 0.3893353331699313,
 0.41145542822976316,
 0.4112914349104291,
 0.3882619244815715,
 0.37999463727830923,
 0.4031290719499544,
 0.4421954314839211,
 0.39007483926166003,
 0.39614311053765666,
 0.47389827089311504,
 0.37882131032326116,
 0.4362025798751119,
 0.38030196103502145,
 0.3858141767309139,
 0.3907699186360029,
 0.3846724240299326,
 0.4006386250600848,
 0.4269388187275853,
 0.4006385109884095,
 0.42321503967642826,
 0.3761990709999019,
 0.4086764351177595,
 0.3910635293229921,
 0.379268435952333,
 0.3848657521058219,
 0.40254327986656724,
 0.41829223261558635,
 0.37850542277367316,
 0.40866310638393977,
 0.41017492867531974,
 0.41971509926186357,
 0.3822007690422315,
 0.4091375334484277,
 0.39083309017882517,
 0.40613169238332303,
 0.39722334891723454,
 0.41281986065224124,
 0.37723850388385405,
 0.39384845035815036,
 0.39393464852284316,
 0.3779982823885289,
 0.3858554204352905,
 0.4466564291823378,
 0.38016702998331814,
 0.3797951018111192,
 0.37442645672335756,
 0.3751165144640972,
 0.43448406463046885,
 0.37542932563405934,
 0.6446681317479691,
 0.44944808347020054,
 0.5415762458807979,
 0.45300017974492385,
 0.5425113289841973,
 0.6210315883948898,
 0.4472155787906994,
 0.5384789683176668,
 0.49138355588321453,
 0.6812746230917515,
 0.46828586942164957,
 0.45643548308932547,
 0.5073884132212829,
 0.48024029940364316,
 0.5751518964947889,
 0.5472091528713793,
 0.4484908248242079,
 0.6873908875974906,
 0.7026997378642189,
 0.4402263112146722,
 0.5730903041260484,
 0.465714993506486,
 0.6215636163426975,
 0.4244149139343905,
 0.5239842090585827,
 0.511489918092921,
 0.41772258045694755,
 0.4180019223861874,
 0.5085963471348357,
 0.47867280743875434,
 0.5391113368283017,
 0.6397502575471153,
 0.532925313262351,
 0.40204017104368894,
 0.44268834973062626,
 0.6292603722833396,
 0.596373129425161,
 0.4488479867978655,
 0.41621736867268905,
 0.5070136715199812,
 0.59055990959213,
 0.5492168379722612,
 0.44944808347020054,
 0.5824182089484028,
 0.6314074632282131,
 0.5455983177220518,
 0.45646612244198853,
 0.46671760590328937,
 0.559229162683811,
 0.42643693580466374]

In [ ]:
clusters=[]
for i in range(149):
    temp=[]
    for j in range(149):
        if(average[i]<=sim_matrix[i][j]):
            temp.append(j)

    clusters.append(temp)

In [ ]:
clusters_df=pd.DataFrame(clusters)
clusters_df

,0,1,2,3,4,5,6,7,8,9,...,81,82,83,84,85,86,87,88,89,90
0,49,50,51,52,53,54,55,57,58,60,...,144.0,145.0,146.0,147.0,148.0,NaN,NaN,NaN,NaN,NaN
1,49,50,51,52,53,54,55,57,58,60,...,142.0,143.0,144.0,145.0,146.0,147.0,148.0,NaN,NaN,NaN
2,49,50,51,52,53,54,55,57,58,60,...,144.0,145.0,146.0,147.0,148.0,NaN,NaN,NaN,NaN,NaN
3,49,50,51,52,53,54,55,57,58,60,...,141.0,142.0,143.0,144.0,145.0,146.0,147.0,148.0,NaN,NaN
4,49,50,51,52,53,54,55,57,58,59,...,144.0,145.0,146.0,147.0,148.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
clusters[0] #this is the 0th cluster which is centering the 0th object

[49,
 50,
 51,
 52,
 53,
 54,
 55,
 57,
 58,
 60,
 62,
 64,
 65,
 67,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 93,
 95,
 96,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148]

In [ ]:
print(len(clusters[0])) #this is the size of the 0th cluster

86

In [ ]:
clusters[55] #this is the 55th cluster

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 56,
 59,
 92,
 99,
 108,
 116,
 117]

In [ ]:
len(clusters[55]) #size of the 55th cluster

56

In [ ]:
#now we have to remove some clusters
#lets say there are clusters A and B and if A contains all the elements of
#B and len(A)>=len(B) that means B is subset cluster of A
def f(a, b):
    a.sort()
    b.sort()

    if len(a) < len(b):
        return False #is a is lesser in size then b cannot be a subcluster to it

    for i in b:
        if i not in a:
            return False

    return True

In [ ]:
clusters[1]

[49,
 50,
 51,
 52,
 53,
 54,
 55,
 57,
 58,
 60,
 62,
 64,
 65,
 67,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 93,
 94,
 95,
 96,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148]

In [ ]:
if(f(clusters[0],clusters[1])):   #return true because the clusters are fully overlapping
    print("yes")

In [ ]:
len(clusters) #for every cluster of this clusters we keep a boolean value which marks true if that is subcluster of any other cluster

149

In [ ]:
#clusters.sort(key=lambda x: len(x), reverse=True) #taking the maxsize clusters in the front
duplicates=[]
for i in range(149):
    duplicates.append(False)
for i in range(149):
    if(duplicates[i]):
        continue;
    for j in range(149):
        if(i==j):
            continue
        if(f(clusters[i],clusters[j])):
            duplicates[j]=True
            print(j,"is a subcluster of",i)

2 is a subcluster of 0
5 is a subcluster of 0
7 is a subcluster of 0
19 is a subcluster of 0
22 is a subcluster of 0
23 is a subcluster of 0
24 is a subcluster of 0
25 is a subcluster of 0
28 is a subcluster of 0
29 is a subcluster of 0
30 is a subcluster of 0
37 is a subcluster of 0
40 is a subcluster of 0
42 is a subcluster of 0
44 is a subcluster of 0
0 is a subcluster of 1
2 is a subcluster of 1
5 is a subcluster of 1
6 is a subcluster of 1
7 is a subcluster of 1
8 is a subcluster of 1
10 is a subcluster of 1
11 is a subcluster of 1
12 is a subcluster of 1
19 is a subcluster of 1
22 is a subcluster of 1
23 is a subcluster of 1
24 is a subcluster of 1
25 is a subcluster of 1
27 is a subcluster of 1
28 is a subcluster of 1
29 is a subcluster of 1
30 is a subcluster of 1
33 is a subcluster of 1
34 is a subcluster of 1
35 is a subcluster of 1
36 is a subcluster of 1
37 is a subcluster of 1
38 is a subcluster of 1
40 is a subcluster of 1
41 is a subcluster of 1
42 is a subcluster of 1
44 is a subcluster of 1
46 is a subcluster of 1
48 is a subcluster of 1
0 is a subcluster of 3
1 is a subcluster of 3
2 is a subcluster of 3
5 is a subcluster of 3
6 is a subcluster of 3
7 is a subcluster of 3
8 is a subcluster of 3
9 is a subcluster of 3
10 is a subcluster of 3
11 is a subcluster of 3
12 is a subcluster of 3
16 is a subcluster of 3
17 is a subcluster of 3
18 is a subcluster of 3
19 is a subcluster of 3
20 is a subcluster of 3
22 is a subcluster of 3
23 is a subcluster of 3
24 is a subcluster of 3
25 is a subcluster of 3
26 is a subcluster of 3
27 is a subcluster of 3
28 is a subcluster of 3
29 is a subcluster of 3
30 is a subcluster of 3
33 is a subcluster of 3
34 is a subcluster of 3
35 is a subcluster of 3
36 is a subcluster of 3
37 is a subcluster of 3
38 is a subcluster of 3
39 is a subcluster of 3
40 is a subcluster of 3
41 is a subcluster of 3
42 is a subcluster of 3
43 is a subcluster of 3
44 is a subcluster of 3
45 is a subcluster of 3
46 is a subcluster of 3
47 is a subcluster of 3
48 is a subcluster of 3
22 is a subcluster of 4
30 is a subcluster of 4
40 is a subcluster of 4
42 is a subcluster of 4
43 is a subcluster of 4
0 is a subcluster of 13
2 is a subcluster of 13
4 is a subcluster of 13
5 is a subcluster of 13
7 is a subcluster of 13
9 is a subcluster of 13
10 is a subcluster of 13
14 is a subcluster of 13
15 is a subcluster of 13
16 is a subcluster of 13
17 is a subcluster of 13
18 is a subcluster of 13
19 is a subcluster of 13
20 is a subcluster of 13
22 is a subcluster of 13
23 is a subcluster of 13
24 is a subcluster of 13
25 is a subcluster of 13
28 is a subcluster of 13
29 is a subcluster of 13
30 is a subcluster of 13
32 is a subcluster of 13
37 is a subcluster of 13
40 is a subcluster of 13
42 is a subcluster of 13
43 is a subcluster of 13
44 is a subcluster of 13
45 is a subcluster of 13
47 is a subcluster of 13
0 is a subcluster of 21
1 is a subcluster of 21
2 is a subcluster of 21
3 is a subcluster of 21
5 is a subcluster of 21
6 is a subcluster of 21
7 is a subcluster of 21
8 is a subcluster of 21
9 is a subcluster of 21
10 is a subcluster of 21
11 is a subcluster of 21
12 is a subcluster of 21
16 is a subcluster of 21
17 is a subcluster of 21
18 is a subcluster of 21
19 is a subcluster of 21
20 is a subcluster of 21
22 is a subcluster of 21
23 is a subcluster of 21
24 is a subcluster of 21
25 is a subcluster of 21
26 is a subcluster of 21
27 is a subcluster of 21
28 is a subcluster of 21
29 is a subcluster of 21
30 is a subcluster of 21
33 is a subcluster of 21
34 is a subcluster of 21
35 is a subcluster of 21
36 is a subcluster of 21
37 is a subcluster of 21
38 is a subcluster of 21
39 is a subcluster of 21
40 is a subcluster of 21
41 is a subcluster of 21
42 is a subcluster of 21
43 is a subcluster of 21
44 is a subcluster of 21
45 is a subcluster of 21
46 is a subcluster of 21
47 is a subcluster of 21
48 is a subcluster of 21
0 is a subcluster of 31
2 is a subcluster of 31
4 is a subcluster of 31
5 is a subcluster of 31
7 is a subcluster of 31
9 is a subcluster of 31
10 is a subcluster of 31
13 is a subcluster of 31
14 is a subcluster of 31
15 is a subcluster of 31
16 is a subcluster of 31
17 is a subcluster of 31
18 is a subcluster of 31
19 is a subcluster of 31
20 is a subcluster of 31
22 is a subcluster of 31
23 is a subcluster of 31
24 is a subcluster of 31
25 is a subcluster of 31
28 is a subcluster of 31
29 is a subcluster of 31
30 is a subcluster of 31
32 is a subcluster of 31
37 is a subcluster of 31
40 is a subcluster of 31
42 is a subcluster of 31
43 is a subcluster of 31
44 is a subcluster of 31
45 is a subcluster of 31
47 is a subcluster of 31
55 is a subcluster of 49
85 is a subcluster of 49
112 is a subcluster of 49
120 is a subcluster of 49
122 is a subcluster of 49
125 is a subcluster of 49
137 is a subcluster of 49
53 is a subcluster of 50
71 is a subcluster of 50
82 is a subcluster of 50
105 is a subcluster of 50
118 is a subcluster of 50
132 is a subcluster of 50
133 is a subcluster of 50
55 is a subcluster of 51
69 is a subcluster of 51
76 is a subcluster of 51
100 is a subcluster of 51
107 is a subcluster of 51
110 is a subcluster of 51
112 is a subcluster of 51
120 is a subcluster of 51
122 is a subcluster of 51
125 is a subcluster of 51
126 is a subcluster of 51
128 is a subcluster of 51
137 is a subcluster of 51
141 is a subcluster of 51
145 is a subcluster of 51
148 is a subcluster of 51
53 is a subcluster of 52
54 is a subcluster of 52
57 is a subcluster of 52
58 is a subcluster of 52
60 is a subcluster of 52
62 is a subcluster of 52
64 is a subcluster of 52
65 is a subcluster of 52
67 is a subcluster of 52
70 is a subcluster of 52
71 is a subcluster of 52
72 is a subcluster of 52
73 is a subcluster of 52
74 is a subcluster of 52
75 is a subcluster of 52
77 is a subcluster of 52
82 is a subcluster of 52
83 is a subcluster of 52
86 is a subcluster of 52
87 is a subcluster of 52
88 is a subcluster of 52
89 is a subcluster of 52
90 is a subcluster of 52
93 is a subcluster of 52
94 is a subcluster of 52
95 is a subcluster of 52
96 is a subcluster of 52
98 is a subcluster of 52
105 is a subcluster of 52
118 is a subcluster of 52
132 is a subcluster of 52
133 is a subcluster of 52
52 is a subcluster of 61
53 is a subcluster of 61
54 is a subcluster of 61
57 is a subcluster of 61
58 is a subcluster of 61
60 is a subcluster of 61
62 is a subcluster of 61
64 is a subcluster of 61
65 is a subcluster of 61
67 is a subcluster of 61
70 is a subcluster of 61
71 is a subcluster of 61
72 is a subcluster of 61
73 is a subcluster of 61
74 is a subcluster of 61
75 is a subcluster of 61
77 is a subcluster of 61
82 is a subcluster of 61
83 is a subcluster of 61
86 is a subcluster of 61
87 is a subcluster of 61
88 is a subcluster of 61
89 is a subcluster of 61
90 is a subcluster of 61
91 is a subcluster of 61
93 is a subcluster of 61
94 is a subcluster of 61
95 is a subcluster of 61
96 is a subcluster of 61
98 is a subcluster of 61
105 is a subcluster of 61
118 is a subcluster of 61
132 is a subcluster of 61
133 is a subcluster of 61
52 is a subcluster of 63
53 is a subcluster of 63
54 is a subcluster of 63
57 is a subcluster of 63
58 is a subcluster of 63
60 is a subcluster of 63
62 is a subcluster of 63
64 is a subcluster of 63
65 is a subcluster of 63
67 is a subcluster of 63
70 is a subcluster of 63
71 is a subcluster of 63
72 is a subcluster of 63
73 is a subcluster of 63
74 is a subcluster of 63
75 is a subcluster of 63
77 is a subcluster of 63
82 is a subcluster of 63
83 is a subcluster of 63
86 is a subcluster of 63
87 is a subcluster of 63
88 is a subcluster of 63
89 is a subcluster of 63
90 is a subcluster of 63
93 is a subcluster of 63
94 is a subcluster of 63
95 is a subcluster of 63
96 is a subcluster of 63
98 is a subcluster of 63
105 is a subcluster of 63
118 is a subcluster of 63
132 is a subcluster of 63
133 is a subcluster of 63
52 is a subcluster of 66
53 is a subcluster of 66
54 is a subcluster of 66
57 is a subcluster of 66
58 is a subcluster of 66
60 is a subcluster of 66
62 is a subcluster of 66
64 is a subcluster of 66
65 is a subcluster of 66
67 is a subcluster of 66
70 is a subcluster of 66
71 is a subcluster of 66
72 is a subcluster of 66
73 is a subcluster of 66
74 is a subcluster of 66
75 is a subcluster of 66
77 is a subcluster of 66
81 is a subcluster of 66
82 is a subcluster of 66
83 is a subcluster of 66
86 is a subcluster of 66
87 is a subcluster of 66
88 is a subcluster of 66
89 is a subcluster of 66
90 is a subcluster of 66
91 is a subcluster of 66
93 is a subcluster of 66
94 is a subcluster of 66
95 is a subcluster of 66
96 is a subcluster of 66
98 is a subcluster of 66
105 is a subcluster of 66
118 is a subcluster of 66
132 is a subcluster of 66
133 is a subcluster of 66
52 is a subcluster of 68
53 is a subcluster of 68
54 is a subcluster of 68
57 is a subcluster of 68
58 is a subcluster of 68
60 is a subcluster of 68
62 is a subcluster of 68
63 is a subcluster of 68
64 is a subcluster of 68
65 is a subcluster of 68
67 is a subcluster of 68
70 is a subcluster of 68
71 is a subcluster of 68
72 is a subcluster of 68
73 is a subcluster of 68
74 is a subcluster of 68
75 is a subcluster of 68
77 is a subcluster of 68
81 is a subcluster of 68
82 is a subcluster of 68
83 is a subcluster of 68
86 is a subcluster of 68
87 is a subcluster of 68
88 is a subcluster of 68
89 is a subcluster of 68
90 is a subcluster of 68
91 is a subcluster of 68
93 is a subcluster of 68
94 is a subcluster of 68
95 is a subcluster of 68
96 is a subcluster of 68
98 is a subcluster of 68
105 is a subcluster of 68
118 is a subcluster of 68
132 is a subcluster of 68
133 is a subcluster of 68
52 is a subcluster of 79
53 is a subcluster of 79
54 is a subcluster of 79
57 is a subcluster of 79
58 is a subcluster of 79
60 is a subcluster of 79
62 is a subcluster of 79
63 is a subcluster of 79
64 is a subcluster of 79
65 is a subcluster of 79
67 is a subcluster of 79
68 is a subcluster of 79
70 is a subcluster of 79
71 is a subcluster of 79
72 is a subcluster of 79
73 is a subcluster of 79
74 is a subcluster of 79
75 is a subcluster of 79
77 is a subcluster of 79
81 is a subcluster of 79
82 is a subcluster of 79
83 is a subcluster of 79
86 is a subcluster of 79
87 is a subcluster of 79
88 is a subcluster of 79
89 is a subcluster of 79
90 is a subcluster of 79
91 is a subcluster of 79
93 is a subcluster of 79
94 is a subcluster of 79
95 is a subcluster of 79
96 is a subcluster of 79
98 is a subcluster of 79
105 is a subcluster of 79
118 is a subcluster of 79
132 is a subcluster of 79
133 is a subcluster of 79
82 is a subcluster of 84
105 is a subcluster of 84
132 is a subcluster of 84
133 is a subcluster of 84
56 is a subcluster of 92
76 is a subcluster of 99
100 is a subcluster of 99
101 is a subcluster of 99
102 is a subcluster of 99
103 is a subcluster of 99
104 is a subcluster of 99
106 is a subcluster of 99
107 is a subcluster of 99
108 is a subcluster of 99
109 is a subcluster of 99
110 is a subcluster of 99
111 is a subcluster of 99
112 is a subcluster of 99
113 is a subcluster of 99
114 is a subcluster of 99
115 is a subcluster of 99
117 is a subcluster of 99
119 is a subcluster of 99
120 is a subcluster of 99
121 is a subcluster of 99
123 is a subcluster of 99
124 is a subcluster of 99
126 is a subcluster of 99
127 is a subcluster of 99
128 is a subcluster of 99
129 is a subcluster of 99
130 is a subcluster of 99
131 is a subcluster of 99
134 is a subcluster of 99
135 is a subcluster of 99
136 is a subcluster of 99
138 is a subcluster of 99
139 is a subcluster of 99
140 is a subcluster of 99
141 is a subcluster of 99
142 is a subcluster of 99
143 is a subcluster of 99
144 is a subcluster of 99
145 is a subcluster of 99
146 is a subcluster of 99
147 is a subcluster of 99
148 is a subcluster of 99
76 is a subcluster of 116
99 is a subcluster of 116
100 is a subcluster of 116
101 is a subcluster of 116
102 is a subcluster of 116
103 is a subcluster of 116
104 is a subcluster of 116
106 is a subcluster of 116
107 is a subcluster of 116
108 is a subcluster of 116
109 is a subcluster of 116
110 is a subcluster of 116
111 is a subcluster of 116
112 is a subcluster of 116
113 is a subcluster of 116
114 is a subcluster of 116
115 is a subcluster of 116
117 is a subcluster of 116
119 is a subcluster of 116
120 is a subcluster of 116
121 is a subcluster of 116
123 is a subcluster of 116
124 is a subcluster of 116
126 is a subcluster of 116
127 is a subcluster of 116
128 is a subcluster of 116
129 is a subcluster of 116
130 is a subcluster of 116
131 is a subcluster of 116
134 is a subcluster of 116
135 is a subcluster of 116
136 is a subcluster of 116
138 is a subcluster of 116
139 is a subcluster of 116
140 is a subcluster of 116
141 is a subcluster of 116
142 is a subcluster of 116
143 is a subcluster of 116
144 is a subcluster of 116
145 is a subcluster of 116
146 is a subcluster of 116
147 is a subcluster of 116
148 is a subcluster of 116

In [ ]:
duplicates

[True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [ ]:
col=[]
for i in range(149):
    if(duplicates[i]==False):
        col.append(i)
#differentiating out the unique clusters

In [ ]:
len(col)

15

In [ ]:
unique_clusters=[]
for i in range(149):
    if(duplicates[i]==False):
        unique_clusters.append(clusters[i])

In [ ]:
unique_cluster_df=pd.DataFrame(unique_clusters)

In [ ]:
unique_cluster_df #only 15 clusters in the newly formed unique_clusters

,0,1,2,3,4,5,6,7,8,9,...,81,82,83,84,85,86,87,88,89,90
0,49,50,51,52,53,54,55,57,58,60,...,140.0,141.0,142.0,143.0,144.0,145.0,146.0,147.0,148.0,NaN
1,49,50,51,52,53,54,55,57,58,59,...,139.0,140.0,141.0,142.0,143.0,144.0,145.0,146.0,147.0,148.0
2,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0,1,2,3,4,5,6,7,8,9,...,144.0,146.0,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0,1,2,3,4,5,6,7,8,9,...,146.0,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0,1,2,3,4,5,6,7,8,9,...,141.0,142.0,143.0,144.0,145.0,146.0,147.0,NaN,NaN,NaN
9,0,1,2,3,4,5,6,7,8,9,...,144.0,146.0,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0,1,2,3,4,5,6,7,8,9,...,140.0,141.0,142.0,143.0,144.0,146.0,147.0,NaN,NaN,NaN
11,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0,1,2,3,4,5,6,7,8,9,...,144.0,145.0,146.0,147.0,148.0,NaN,NaN,NaN,NaN,NaN
13,0,1,2,3,4,5,6,7,8,9,...,145.0,146.0,147.0,148.0,NaN,NaN,NaN,NaN,NaN,NaN
14,0,1,2,3,4,5,6,7,8,9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
def intersection(a, b):
    ans = 0
    for i in a:
        if i in b:
            ans += 1
    return ans

def unionval(a, b):
    intersect = intersection(a, b)
    return len(a) + len(b) - intersect

In [ ]:
#now for each of this cluster we need to find the similarity value with every other cluster
#creating a 15*15 similarity matrix
C=[] #similarity matrix for the clusters
for i in range(15):
    temp=[]
    for j in range(15):
        if(i==j):
            temp.append(1)
        else:
            temp.append(intersection(unique_clusters[i],unique_clusters[j])/unionval(unique_clusters[i],unique_clusters[j]))

    C.append(temp)

In [ ]:
df5=pd.DataFrame(C)
df5

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,1.000000,0.967391,0.063380,0.078571,0.034965,0.288889,0.230216,0.244604,0.299270,0.251799,0.289855,0.063830,0.343511,0.325758,0.013514
1,0.967391,1.000000,0.070423,0.085714,0.041958,0.286765,0.228571,0.242857,0.297101,0.250000,0.287770,0.070922,0.340909,0.323308,0.027211
2,0.063380,0.070423,1.000000,0.906250,0.919355,0.593407,0.690476,0.674419,0.602151,0.666667,0.619565,0.890625,0.515464,0.536842,0.753623
3,0.078571,0.085714,0.906250,1.000000,0.859375,0.629213,0.731707,0.714286,0.637363,0.705882,0.655556,0.951613,0.547368,0.569892,0.704225
4,0.034965,0.041958,0.919355,0.859375,1.000000,0.543478,0.635294,0.620690,0.553191,0.613636,0.569892,0.903226,0.469388,0.489583,0.815385
5,0.288889,0.286765,0.593407,0.629213,0.543478,1.000000,0.875000,0.897727,0.932584,0.909091,0.932584,0.600000,0.888889,0.898876,0.454545
6,0.230216,0.228571,0.690476,0.731707,0.635294,0.875000,1.000000,0.952381,0.877778,0.941176,0.898876,0.698795,0.776596,0.804348,0.532609
7,0.244604,0.242857,0.674419,0.714286,0.620690,0.897727,0.952381,1.000000,0.900000,0.919540,0.921348,0.682353,0.797872,0.826087,0.521277
8,0.299270,0.297101,0.602151,0.637363,0.553191,0.932584,0.877778,0.900000,1.000000,0.911111,0.977528,0.608696,0.891304,0.922222,0.465347
9,0.251799,0.250000,0.666667,0.705882,0.613636,0.909091,0.941176,0.919540,0.911111,1.000000,0.932584,0.674419,0.808511,0.836957,0.515789
10,0.289855,0.287770,0.619565,0.655556,0.569892,0.932584,0.898876,0.921348,0.977528,0.932584,1.000000,0.626374,0.870968,0.901099,0.480000
11,0.063830,0.070922,0.890625,0.951613,0.903226,0.600000,0.698795,0.682353,0.608696,0.674419,0.626374,1.000000,0.520833,0.542553,0.739130
12,0.343511,0.340909,0.515464,0.547368,0.469388,0.888889,0.776596,0.797872,0.891304,0.808511,0.870968,0.520833,1.000000,0.965517,0.390476
13,0.325758,0.323308,0.536842,0.569892,0.489583,0.898876,0.804348,0.826087,0.922222,0.836957,0.901099,0.542553,0.965517,1.000000,0.407767
14,0.013514,0.027211,0.753623,0.704225,0.815385,0.454545,0.532609,0.521277,0.465347,0.515789,0.480000,0.739130,0.390476,0.407767,1.000000

In [ ]:
def merge(a, b):
    for i in b:
        if i not in a:
            a.append(i)
    return a

In [ ]:
df5[0][2]

0.06338028169014084

In [ ]:
len(df5)

15

In [ ]:
maxi=-1e9
row=0
col=0
for i in range (14):
    for j in range (14):
        if(i==j):
            continue
        else:
            if(df5[i][j]>maxi):
                maxi=df5[i][j]
                row=i
                col=j
print(df5[row][col]) #this stores the maximum value of the cluster
temp1=[]
temp2=[]
#print(type(df5[row])) data type is a series
for i in range (14):
    temp1.append(df5[row][i])
for i  in range (14):
    temp2.append(df5[col][i])

temp3=merge(temp1,temp2)
print(temp3)
temp3=np.array(temp3)
temp3=pd.Series(temp3)
df5=df5.drop([row],axis=0)
df5=df5.drop([col],axis=0)
df5=df5.append(temp3,ignore_index=True)

0.9775280898876404
[0.29927007299270075, 0.2971014492753623, 0.6021505376344086, 0.6373626373626373, 0.5531914893617021, 0.9325842696629213, 0.8777777777777778, 0.9, 1.0, 0.9111111111111111, 0.9775280898876404, 0.6086956521739131, 0.8913043478260869, 0.9222222222222223, 0.2898550724637681, 0.28776978417266186, 0.6195652173913043, 0.6555555555555556, 0.5698924731182796, 0.898876404494382, 0.9213483146067416, 0.6263736263736264, 0.8709677419354839, 0.9010989010989011]

<ipython-input-49-57978c431234>:28: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df5=df5.append(temp3,ignore_index=True)

In [ ]:
len(df5)

14

In [ ]:
df5

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,1.000000,0.967391,0.063380,0.078571,0.034965,0.288889,0.230216,0.244604,0.299270,0.251799,...,0.013514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.967391,1.000000,0.070423,0.085714,0.041958,0.286765,0.228571,0.242857,0.297101,0.250000,...,0.027211,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.063380,0.070423,1.000000,0.906250,0.919355,0.593407,0.690476,0.674419,0.602151,0.666667,...,0.753623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.078571,0.085714,0.906250,1.000000,0.859375,0.629213,0.731707,0.714286,0.637363,0.705882,...,0.704225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.034965,0.041958,0.919355,0.859375,1.000000,0.543478,0.635294,0.620690,0.553191,0.613636,...,0.815385,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.288889,0.286765,0.593407,0.629213,0.543478,1.000000,0.875000,0.897727,0.932584,0.909091,...,0.454545,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.230216,0.228571,0.690476,0.731707,0.635294,0.875000,1.000000,0.952381,0.877778,0.941176,...,0.532609,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0.244604,0.242857,0.674419,0.714286,0.620690,0.897727,0.952381,1.000000,0.900000,0.919540,...,0.521277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0.251799,0.250000,0.666667,0.705882,0.613636,0.909091,0.941176,0.919540,0.911111,1.000000,...,0.515789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0.063830,0.070922,0.890625,0.951613,0.903226,0.600000,0.698795,0.682353,0.608696,0.674419,...,0.739130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0.343511,0.340909,0.515464,0.547368,0.469388,0.888889,0.776596,0.797872,0.891304,0.808511,...,0.390476,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.325758,0.323308,0.536842,0.569892,0.489583,0.898876,0.804348,0.826087,0.922222,0.836957,...,0.407767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0.013514,0.027211,0.753623,0.704225,0.815385,0.454545,0.532609,0.521277,0.465347,0.515789,...,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,0.299270,0.297101,0.602151,0.637363,0.553191,0.932584,0.877778,0.900000,1.000000,0.911111,...,0.289855,0.28777,0.619565,0.655556,0.569892,0.898876,0.921348,0.626374,0.870968,0.901099

In [ ]:
maxi=-1e9
row=0
col=0
for i in range (len(df5)):
    for j in range (len(df5[0])):
        if(i==j):
            continue
        else:
            if(df5[i][j]>maxi):
                maxi=df5[i][j]
                row=i
                col=j
print(df5[row][col]) #this stores the maximum value of the cluster
temp1=[]
temp2=[]
#print(type(df5[row])) data type is a series
for i in range (len(df5[0])):
    temp1.append(df5[row][i])
for i  in range (len(df5[0])):
    temp2.append(df5[col][i])

temp3=merge(temp1,temp2)
print(temp3)
temp3=np.array(temp3)
temp3=pd.Series(temp3)
df5=df5.drop([row],axis=0)
df5=df5.drop([col],axis=0)
df5=df5.append(temp3,ignore_index=True)

1.0
[0.29927007299270075, 0.2971014492753623, 0.6021505376344086, 0.6373626373626373, 0.5531914893617021, 0.9325842696629213, 0.8777777777777778, 0.9, 0.9111111111111111, 0.6086956521739131, 0.8913043478260869, 0.9222222222222223, 0.46534653465346537, 1.0, 0.32575757575757575, 0.3233082706766917, 0.5368421052631579, 0.5698924731182796, 0.4895833333333333, 0.898876404494382, 0.8043478260869565, 0.8260869565217391, 0.8369565217391305, 0.5425531914893617, 0.9655172413793104, 0.4077669902912621]

<ipython-input-52-bd8e1589de00>:28: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df5=df5.append(temp3,ignore_index=True)

In [ ]:
len(df5)

13

In [ ]:
df5

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.000000,0.967391,0.063380,0.078571,0.034965,0.288889,0.230216,0.244604,0.299270,0.251799,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.967391,1.000000,0.070423,0.085714,0.041958,0.286765,0.228571,0.242857,0.297101,0.250000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.063380,0.070423,1.000000,0.906250,0.919355,0.593407,0.690476,0.674419,0.602151,0.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.078571,0.085714,0.906250,1.000000,0.859375,0.629213,0.731707,0.714286,0.637363,0.705882,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.034965,0.041958,0.919355,0.859375,1.000000,0.543478,0.635294,0.620690,0.553191,0.613636,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.288889,0.286765,0.593407,0.629213,0.543478,1.000000,0.875000,0.897727,0.932584,0.909091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.230216,0.228571,0.690476,0.731707,0.635294,0.875000,1.000000,0.952381,0.877778,0.941176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0.244604,0.242857,0.674419,0.714286,0.620690,0.897727,0.952381,1.000000,0.900000,0.919540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0.063830,0.070922,0.890625,0.951613,0.903226,0.600000,0.698795,0.682353,0.608696,0.674419,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0.343511,0.340909,0.515464,0.547368,0.469388,0.888889,0.776596,0.797872,0.891304,0.808511,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0.325758,0.323308,0.536842,0.569892,0.489583,0.898876,0.804348,0.826087,0.922222,0.836957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0.013514,0.027211,0.753623,0.704225,0.815385,0.454545,0.532609,0.521277,0.465347,0.515789,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0.299270,0.297101,0.602151,0.637363,0.553191,0.932584,0.877778,0.900000,0.911111,0.608696,...,0.536842,0.569892,0.489583,0.898876,0.804348,0.826087,0.836957,0.542553,0.965517,0.407767

In [ ]:
maxi=-1e9
row=0
col=0
for i in range (len(df5)):
    for j in range (len(df5[0])):
        if(i==j):
            continue
        else:
            if(df5[i][j]>maxi):
                maxi=df5[i][j]
                row=i
                col=j
print(df5[row][col]) #this stores the maximum value of the cluster
temp1=[]
temp2=[]
#print(type(df5[row])) data type is a series
for i in range (len(df5[0])):
    temp1.append(df5[row][i])
for i  in range (len(df5[0])):
    temp2.append(df5[col][i])

temp3=merge(temp1,temp2)
print(temp3)
temp3=np.array(temp3)
temp3=pd.Series(temp3)
df5=df5.drop([row],axis=0)
df5=df5.drop([col],axis=0)
df5=df5.append(temp3,ignore_index=True)

1.0
[0.06382978723404255, 0.07092198581560284, 0.890625, 0.9516129032258065, 0.9032258064516129, 0.6, 0.6987951807228916, 0.6823529411764706, 1.0, 0.5208333333333334, 0.5425531914893617, 0.7391304347826086, 0.9222222222222223, 0.29927007299270075, 0.2971014492753623, 0.6021505376344086, 0.6373626373626373, 0.5531914893617021, 0.9325842696629213, 0.8777777777777778, 0.9, 0.6086956521739131, 0.8913043478260869, 0.46534653465346537, 0.9111111111111111]

<ipython-input-55-bd8e1589de00>:28: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df5=df5.append(temp3,ignore_index=True)

In [ ]:
df5

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,1.000000,0.967391,0.063380,0.078571,0.034965,0.288889,0.230216,0.244604,0.299270,0.251799,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.967391,1.000000,0.070423,0.085714,0.041958,0.286765,0.228571,0.242857,0.297101,0.250000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.063380,0.070423,1.000000,0.906250,0.919355,0.593407,0.690476,0.674419,0.602151,0.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.078571,0.085714,0.906250,1.000000,0.859375,0.629213,0.731707,0.714286,0.637363,0.705882,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.034965,0.041958,0.919355,0.859375,1.000000,0.543478,0.635294,0.620690,0.553191,0.613636,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.288889,0.286765,0.593407,0.629213,0.543478,1.000000,0.875000,0.897727,0.932584,0.909091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.230216,0.228571,0.690476,0.731707,0.635294,0.875000,1.000000,0.952381,0.877778,0.941176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0.244604,0.242857,0.674419,0.714286,0.620690,0.897727,0.952381,1.000000,0.900000,0.919540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0.343511,0.340909,0.515464,0.547368,0.469388,0.888889,0.776596,0.797872,0.891304,0.808511,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,0.325758,0.323308,0.536842,0.569892,0.489583,0.898876,0.804348,0.826087,0.922222,0.836957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0.299270,0.297101,0.602151,0.637363,0.553191,0.932584,0.877778,0.900000,0.911111,0.608696,...,0.536842,0.569892,0.489583,0.898876,0.804348,0.826087,0.836957,0.542553,0.965517,0.407767
11,0.063830,0.070922,0.890625,0.951613,0.903226,0.600000,0.698795,0.682353,1.000000,0.520833,...,0.637363,0.553191,0.932584,0.877778,0.900000,0.608696,0.891304,0.465347,0.911111,NaN

In [ ]:
maxi=-1e9
row=0
col=0
for i in range (len(df5)):
    for j in range (len(df5[0])):
        if(i==j):
            continue
        else:
            if(df5[i][j]>maxi):
                maxi=df5[i][j]
                row=i
                col=j
print(df5[row][col]) #this stores the maximum value of the cluster
temp1=[]
temp2=[]
#print(type(df5[row])) data type is a series
for i in range (len(df5[0])):
    temp1.append(df5[row][i])
for i  in range (len(df5[0])):
    temp2.append(df5[col][i])

temp3=merge(temp1,temp2)
print(temp3)
temp3=np.array(temp3)
temp3=pd.Series(temp3)
df5=df5.drop([row],axis=0)
df5=df5.drop([col],axis=0)
df5=df5.append(temp3,ignore_index=True)

1.0
[0.29927007299270075, 0.2971014492753623, 0.6021505376344086, 0.6373626373626373, 0.5531914893617021, 0.9325842696629213, 0.8777777777777778, 0.9, 0.8913043478260869, 0.9222222222222223, 0.9111111111111111, 1.0, 0.06382978723404255, 0.07092198581560284, 0.890625, 0.9516129032258065, 0.9032258064516129, 0.6, 0.6987951807228916, 0.6823529411764706, 0.5208333333333334, 0.5425531914893617, 0.7391304347826086]

<ipython-input-57-bd8e1589de00>:28: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df5=df5.append(temp3,ignore_index=True)

In [ ]:
maxi=-1e9
row=0
col=0
for i in range (len(df5)):
    for j in range (len(df5[0])):
        if(i==j):
            continue
        else:
            if(df5[i][j]>maxi):
                maxi=df5[i][j]
                row=i
                col=j
print(df5[row][col]) #this stores the maximum value of the cluster
temp1=[]
temp2=[]
#print(type(df5[row])) data type is a series
for i in range (len(df5[0])):
    temp1.append(df5[row][i])
for i  in range (len(df5[0])):
    temp2.append(df5[col][i])

temp3=merge(temp1,temp2)
print(temp3)
temp3=np.array(temp3)
temp3=pd.Series(temp3)
df5=df5.drop([row],axis=0)
df5=df5.drop([col],axis=0)
df5=df5.append(temp3,ignore_index=True)

0.967391304347826
[1.0, 0.967391304347826, 0.06338028169014084, 0.07857142857142857, 0.03496503496503497, 0.28888888888888886, 0.2302158273381295, 0.2446043165467626, 0.32575757575757575, 0.29927007299270075, 0.29927007299270075, 0.07042253521126761, 0.08571428571428572, 0.04195804195804196, 0.2867647058823529, 0.22857142857142856, 0.24285714285714285, 0.3233082706766917, 0.2971014492753623]

<ipython-input-58-bd8e1589de00>:28: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df5=df5.append(temp3,ignore_index=True)

In [ ]:
df5

,0,1,2,3,4,5,6,7,8,9,...,16,17,18,19,20,21,22,23,24,25
0,0.063380,0.070423,1.000000,0.906250,0.919355,0.593407,0.690476,0.674419,0.602151,0.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.078571,0.085714,0.906250,1.000000,0.859375,0.629213,0.731707,0.714286,0.637363,0.705882,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.034965,0.041958,0.919355,0.859375,1.000000,0.543478,0.635294,0.620690,0.553191,0.613636,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.288889,0.286765,0.593407,0.629213,0.543478,1.000000,0.875000,0.897727,0.932584,0.909091,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.230216,0.228571,0.690476,0.731707,0.635294,0.875000,1.000000,0.952381,0.877778,0.941176,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,0.244604,0.242857,0.674419,0.714286,0.620690,0.897727,0.952381,1.000000,0.900000,0.919540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,0.325758,0.323308,0.536842,0.569892,0.489583,0.898876,0.804348,0.826087,0.922222,0.836957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,0.299270,0.297101,0.602151,0.637363,0.553191,0.932584,0.877778,0.900000,0.911111,0.608696,...,0.536842,0.569892,0.489583,0.898876,0.804348,0.826087,0.836957,0.542553,0.965517,0.407767
8,0.299270,0.297101,0.602151,0.637363,0.553191,0.932584,0.877778,0.900000,0.891304,0.922222,...,0.903226,0.600000,0.698795,0.682353,0.520833,0.542553,0.739130,NaN,NaN,NaN
9,1.000000,0.967391,0.063380,0.078571,0.034965,0.288889,0.230216,0.244604,0.325758,0.299270,...,0.242857,0.323308,0.297101,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
len(df5)

10